spring.application.name=corebanking
spring.docker.compose.lifecycle-management=start_only
spring.jackson.json.write.write-numbers-as-strings=true
mybatis.type-handlers-package=dev.azdanov.corebanking.account.infrastructure.persistence.typehandler