spring.application.name=corebanking
spring.docker.compose.file=docker-compose.yaml
spring.docker.compose.lifecycle-management=start_only
spring.jackson.json.write.write-numbers-as-strings=true
mybatis.type-handlers-package=dev.azdanov.corebanking.account.infrastructure.persistence.typehandler
corebanking.messaging.exchange=corebanking.account.events
corebanking.outbox.relay.fixed-delay=1000
corebanking.outbox.relay.batch-size=100
corebanking.outbox.relay.max-attempts=10